### ISSUE TITLE
Fix gulp watch

### ISSUE THREAD

**Issue by banoodle** [kanopi/drupal-starter#3]
Problem: gulp sass and gulp uglify work great, but when you attempt gulp watch, you get this error...

`Error: watching ./sass/**/*.scss: watch task has to be a function (optionally generated by using gulp.parallel or gulp.series)
    at Gulp.watch (/var/www/web/themes/custom/site_theme/node_modules/gulp/index.js:28:11)
    at /var/www/web/themes/custom/site_theme/gulpfile.js:54:8
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/var/www/web/themes/custom/site_theme/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[21:04:42] 'watch' errored after 55 ms`

I researched this error a little and tried implementing the advice I found here: https://stackoverflow.com/a/39665899/2755365

But I couldn't get it to work. The following eliminates the error and even kind of looks like it's watching when you run the command, but nothing actually happens (if I change scss or js - it doesn't get compiled):

`gulp.task('watch', function() {
  livereload.listen();
  gulp.watch('sass/**/*.scss', gulp.series('sass'));
  gulp.watch('lib/*.js', gulp.series('uglify'));
  gulp.watch(['./css/styles.css', './**/*.twig', './js/*.js'], function (files){
    livereload.changed(files)
  });
});`

**Comment by thejimbirch** [comment]
I know the gulpfile has gone through some changes since this issue has been posted.  Do we still have this issue says the man that never watches?
